name: repository
description: New Flutter Plugin
version: 1.0.0
author: magazmj<magazmj@gmail.com>
homepage: https://github.com/magazmj/repository

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:

dev_dependencies:
